**Exercise 1:** Create a function that takes 2 numbers as inputs from the keyboard and calculates the greatest common divisor using the Euclidean Algorithm.
> The Euclidean Algorithm:
  1. If a = b, stop.
  2. If a > b, replace a with a - b and go back to step 1.
  3. If b > a, replace b with b - a and go back to step 1.

In [4]:
def greatest_Common_Divisor(number_1, number_2):
  # TO DO: Define two placeholder variables a and b that will take the values
  # of number_1 and number_2 respectively
  a = number_1
  b = number_2
  # TO DO: While the numbers are not equal, replace the largest number by the
  # difference between the larger and the smaller one. Hint: Use
  # if/else statements within a while loop
  while a != b:
    if a > b:
      a = a - b
    else:
      b = b - a

  # TO DO: Assign the result to either a or b, as they are the same at this
  # point
  result = a
  return result

# TO DO: Provide the 2 numbers
# Hint: The input from the keyboard is stored as strings, therefore, we have to
# convert them to integers
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the first number: "))
# TO DO: Call the function and print out the results
result = greatest_Common_Divisor(number_1=num1, number_2=num2)
print("The greatest common divisor is: ", result)

The greatest common divisor is:  12


**Exercise 2:** Create a 4x4 matrix and its transpose using NumPy and multiply them.

In [10]:
# TO DO: Import numpy
import numpy as np
# TO DO: Create the 4x4 matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
# TO DO: Create its transpose
transpose_matrix = np.transpose(matrix)
# TO DO: Multiply the two matrices
result = np.dot(matrix, transpose_matrix)

print("Original Matrix:")
print(matrix)

print("\nTranspose Matrix:")
print(transpose_matrix)

print("\nResult of Multiplication:")
print(result)


Original Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose Matrix:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Result of Multiplication:
[[ 30  70 110 150]
 [ 70 174 278 382]
 [110 278 446 614]
 [150 382 614 846]]


**Exercise 3:** Create a 3x3 identity matrix using NumPy zeros matrix and editing its entries using a for loop.

In [2]:
# TO DO: Create the 3x3 zeros matrix
import numpy as np
matrix = np.zeros((3, 3))
print(matrix) 
# TO DO: Edit the previously created matrix
for i in range(3):
    for j in range(3):
        if i == j:
            matrix[i, j] = 1

print("Identity Matrix:")
print(matrix)           

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Exercise 4:** Create a dataframe that will contain one column with the years from 2015 to 2023 and another column that takes Yes if the year was a leap year. **Hint:** 2016 and 2020 were leap years.

In [6]:
# TO DO: Import pandas
import pandas as pd

years = list(range(2015,2024))

leap_year = []
    
for year in years:
    
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        leap_year.append("Yes")
    else:
        leap_year.append("No")
# TO DO: Create the dataframe

data_frame = pd.DataFrame({"Year":years, "Leap Year": leap_year})

print(data_frame)

   Year Leap Year
0  2015        No
1  2016       Yes
2  2017        No
3  2018        No
4  2019        No
5  2020       Yes
6  2021        No
7  2022        No
8  2023        No


**Exercise 5:**Consider the dataframe created in the codeblock below.

In [7]:
# Consider the dataframe below
race_Stats = {"Winner": ["Max Verstappen", "Sergio Perez", "Max Verstappen"],
              "Pole Sitter": ["Max Verstappen", "Sergio Perez", "Max Verstappen"],
              "Fastest Lap": ["Zhou Guanyu", "Max Verstappen", "Sergio Perez"]}
race_Names = ["Bahrain", "Saudi Arabia", "Australia"]

data_Frame_Race = pd.DataFrame(race_Stats, index = race_Names)

print(data_Frame_Race)

                      Winner     Pole Sitter     Fastest Lap
Bahrain       Max Verstappen  Max Verstappen     Zhou Guanyu
Saudi Arabia    Sergio Perez    Sergio Perez  Max Verstappen
Australia     Max Verstappen  Max Verstappen    Sergio Perez


* Filter the rows and find the following things:
> 1. How many times did the pole sitter win the race.
  2. How many times the winner had the fastest lap.
  3. How many races did Max Verstappen win.

In [8]:
# TO DO: How many times did the pole sitter win the race
pole_sitter_wins = data_Frame_Race[data_Frame_Race['Pole Sitter'] == data_Frame_Race['Winner']].shape[0]
# TO DO: How many times did the winner have the fastest lap
winner_fastest_lap = data_Frame_Race[data_Frame_Race['Winner'] == data_Frame_Race['Fastest Lap']].shape[0]
# TO DO: How many races did Max Verstappen win
max_verstappen_wins = data_Frame_Race[data_Frame_Race['Winner'] == 'Max Verstappen'].shape[0]

print("Number of times the pole sitter won the race:", pole_sitter_wins)
print("Number of times the winner had the fastest lap:", winner_fastest_lap)
print("Number of races Max Verstappen won:", max_verstappen_wins)

Number of times the pole sitter won the race: 3
Number of times the winner had the fastest lap: 0
Number of races Max Verstappen won: 2
